### ISSUE TITLE
Script does not work

### ISSUE THREAD

**Issue by pekaynz** [NetSPI/PowerShell#1]
Hi,

when I run the script I get following errors.

At C:\Windows\System32\Get-FederationEndpoint.ps1:232 char:230
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Windows\System32\Get-FederationEndpoint.ps1:236 char:14
+ </form>      </div>
+              ~
The '<' operator is reserved for future use.
At C:\Windows\System32\Get-FederationEndpoint.ps1:274 char:297
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Windows\System32\Get-FederationEndpoint.ps1:305 char:92
+ ... ss="description">Be notified when participating or @mentioned.</span>
+                                                                   ~
Missing property name after reference operator.
At C:\Windows\System32\Get-FederationEndpoint.ps1:305 char:92
+ ... ss="description">Be notified when participating or @mentioned.</span>
+                                                                   ~
The '<' operator is reserved for future use.
At C:\Windows\System32\Get-FederationEndpoint.ps1:363 char:259
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Windows\System32\Get-FederationEndpoint.ps1:376 char:10
+ </form>  </div>
+          ~
The '<' operator is reserved for future use.
At C:\Windows\System32\Get-FederationEndpoint.ps1:605 char:304
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Windows\System32\Get-FederationEndpoint.ps1:610 char:16
+ </form>        </option></form> ...
+                ~
The '<' operator is reserved for future use.
At C:\Windows\System32\Get-FederationEndpoint.ps1:1104 char:225

**Comment by egru** [comment]
Try using the raw version: https://raw.githubusercontent.com/NetSPI/PowerShell/master/Get-FederationEndpoint.ps1 

Looks like you were pulling down https://github.com/NetSPI/PowerShell/blob/master/Get-FederationEndpoint.ps1. This makes sense as the module does not include HTML and 1000 lines of code.
